"""add embeddings table

Revision ID: 89feba200900
Revises: b3c2d1e0f4a5
Create Date: 2026-06-09 17:25:21.271733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89feba200900'
down_revision: Union[str, Sequence[str], None] = 'b3c2d1e0f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vec', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    # ### end Alembic commands ###
