"""fix: add constraints and updated_at columns

Revision ID: abe8fb90d84c
Revises: e5a6d397de63
Create Date: 2026-06-08 12:36:13.212494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe8fb90d84c'
down_revision: Union[str, Sequence[str], None] = 'e5a6d397de63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_edges', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_unique_constraint('uq_user_edge', 'knowledge_edges', ['user_id', 'source_node_id', 'target_node_id', 'relation_type'])
    op.add_column('knowledge_nodes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('papers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'updated_at')
    op.drop_column('knowledge_nodes', 'updated_at')
    op.drop_constraint('uq_user_edge', 'knowledge_edges', type_='unique')
    op.drop_column('knowledge_edges', 'updated_at')
    # ### end Alembic commands ###
